// <auto-generated>
// Rewired Constants
// This list was generated on 1/27/2024 12:35:51 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveForwardAxis")]
        public const int MoveForwardAxis = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveHorizontalAxis")]
        public const int MoveHorizontalAxis = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Caw")]
        public const int Caw = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 3;
        
    }
}
